### ISSUE TITLE
Some small suggestions :)

### ISSUE THREAD

**Issue by jaeheonshim** [TheVamp/Terraria-Source-Code#1]
The style and paradigms used in this code is highly likely to result in unmaintainable code and/or massive technical debt. I would consider splitting the code into multiple parts rather than putting everything in one file. 

This is sarcasm by the way. Please end my suffering.

**Comment by TheVamp** [comment]
I know that this is a real mess. But back in the days the decompiler was not so good to create super fancy code and I was to lazy to rewrite thousands lines of code.

Terraria was dead in that time and the Dev didn't provide any patches. I remember a bug where you are not able to craft anything from a weapon merchant. This happened when you played with translation. At the end I was so frustrated, that I was more or less forced to patch things by myself using classical reverse engineering techniques. The outcome is this ugly code. (:
